# 1. Import numpy and print the version number

In [ ]:
import numpy as np

# 1. Import numpy and print the version number
print(np.__version__)

2.0.2


# 2. Create a 1D array of numbers from 0 to 9

In [ ]:
arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


# 3. Create a 3x3 numpy array of all True’s

In [ ]:
print(np.ones((3,3), dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# 4. Extract all odd numbers from arr

In [ ]:
print(arr[arr % 2 == 1])          # arr % 2 == 1 returns a Boolean mask for odd numbers only


[1 3 5 7 9]


# 5. Replace all odd numbers in arr with -1

In [ ]:
arr[arr % 2 == 1] = -1            # Directly modifies arr by setting odd positions to -1
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# 6. Replace odd numbers with -1 without changing arr

In [ ]:
arr = np.arange(10)               # Recreate arr to restore original values
out = np.where(arr % 2 == 1, -1, arr)  # np.where(condition, value_if_true, value_if_false)
print(out)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# 7. Convert 1D array to 2D array with 2 rows

In [ ]:
a = np.arange(10).reshape(2, -1)  # reshape(2, -1) → 2 rows, automatically calculates columns
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


# 8. Stack arrays a and b vertically (row-wise)

In [ ]:
b = np.repeat(1, 10).reshape(2, -1)   # b = array of all 1s (shape 2x5)
print(np.vstack([a, b]))              # vstack joins arrays vertically


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# 9. Stack arrays a and b horizontally (column-wise)

In [ ]:
print(np.hstack([a, b]))              # hstack joins arrays side by side


[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


# 10. Create repeating pattern using np.repeat and np.tile

In [ ]:
a = np.array([1,2,3])
out = np.r_[np.repeat(a, 3), np.tile(a, 3)]   # np.r_ combines repeat and tile results in one array
print(out)                                   # Expected pattern generated


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


# 11. Find common elements between two arrays

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))          # np.intersect1d() gives intersection (common items)


[2 4]


# 12. Remove all items in a that are also in b

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a, b))            # np.setdiff1d() finds elements present in a but not in b


[1 2 3 4]


# 13. Get positions where elements of a and b match

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a == b))              # np.where() gives index positions where condition is True


(array([1, 3, 5, 7]),)


14. Get all numbers between 5 and 10 (inclusive)

In [ ]:
a = np.array([2,6,1,9,10,3,27])
print(a[(a >= 5) & (a <= 10)])       # Logical AND (&) filters numbers between 5–10


[ 6  9 10]


15. Swap columns 1 and 2 in a 2D array

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr[:, [1,0,2]])               # arr[:, [1,0,2]] reorders columns (swaps col 0 & 1)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


# 16. Swap rows 1 and 2 in array

In [ ]:
print(arr[[1,0,2], :])               # arr[[1,0,2], :] reorders rows (swaps row 0 & 1)


[[3 4 5]
 [0 1 2]
 [6 7 8]]


# 17. Reverse rows of 2D array

In [ ]:
print(arr[::-1])                     # arr[::-1] reverses the order of rows

[[6 7 8]
 [3 4 5]
 [0 1 2]]


18. Reverse columns of 2D array

In [ ]:
print(arr[:, ::-1])                  # arr[:, ::-1] reverses the order of columns


[[2 1 0]
 [5 4 3]
 [8 7 6]]


19. Create 5x3 array of random decimal numbers between 5 and 10

In [ ]:
rand_arr = np.random.uniform(5, 10, (5,3))  # random.uniform(low, high, shape)
print(rand_arr)


[[6.72759026 9.62977826 5.80109323]
 [5.81126638 5.71845106 5.91196565]
 [6.55678984 7.20548365 8.30464137]
 [9.11195688 9.28063705 8.80912243]
 [6.38084075 9.9211427  9.95840477]]


# 20. Print array rounded to 3 decimal places

In [ ]:
np.set_printoptions(precision=3)     # precision=3 → show only 3 digits after decimal
print(rand_arr)

[[6.728 9.63  5.801]
 [5.811 5.718 5.912]
 [6.557 7.205 8.305]
 [9.112 9.281 8.809]
 [6.381 9.921 9.958]]


 21. Pretty print without scientific notation (e.g. 1e-10)

In [ ]:
np.set_printoptions(suppress=True)   # suppress=True disables scientific notation
print(rand_arr)

[[6.728 9.63  5.801]
 [5.811 5.718 5.912]
 [6.557 7.205 8.305]
 [9.112 9.281 8.809]
 [6.381 9.921 9.958]]


# 22. Limit array display to 6 elements max

In [ ]:
a = np.arange(15)
np.set_printoptions(threshold=6)     # threshold=6 means numpy shows first & last few elements only
print(a)

[ 0  1  2 ... 12 13 14]


23. Print full numpy array without truncation

In [ ]:
np.set_printoptions(threshold=np.inf) # threshold=np.inf → disables truncation
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# 24. Import iris dataset (text intact)

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')  # Reads dataset as text (dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris[:3])                       # Prints first 3 rows

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


# 25. Extract the text column “species”

In [ ]:
species = iris[:, 4]                  # Extract column 5 (index 4)
print(species[:5])

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


26. Convert 1D iris to 2D numeric array (remove species)

In [ ]:
iris_2d = iris[:, :4].astype(float)   # Take first 4 columns & convert to float
print(iris_2d[:3])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


27. Find mean, median, and std of SepalLength (1st column)

In [ ]:
sepallength = iris_2d[:, 0]
print(sepallength.mean(), np.median(sepallength), sepallength.std())  # Mean, median, std

5.843333333333334 5.8 0.8253012917851409


28. Normalize SepalLength between 0 and 1

In [ ]:
norm = (sepallength - sepallength.min()) / (sepallength.max() - sepallength.min())
print(norm[:5])                       # Normalized values between 0 and 1


[0.222 0.167 0.111 0.083 0.194]


29. Find 5th and 95th percentile of SepalLength

In [ ]:
print(np.percentile(sepallength, [5, 95]))   # np.percentile() gives the cut-off values


[4.6   7.255]


30. Insert np.nan at 20 random positions

In [ ]:
iris_2d[np.random.randint(iris_2d.shape[0]), np.random.randint(iris_2d.shape[1])] = np.nan
# Randomly inserts NaN (missing) values in dataset


# 31. Find number and position of missing values in SepalLength

In [ ]:
print(np.isnan(iris_2d[:, 0]).sum())        # Counts how many NaN values
print(np.where(np.isnan(iris_2d[:, 0])))    # Shows index positions of NaN values

0
(array([], dtype=int64),)


# 32. Filter rows where PetalLength >1.5 and SepalLength <5.0

In [ ]:
cond = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
print(iris_2d[cond])                         # Returns rows matching both conditions

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 nan]
 [4.8 nan 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


33. Select rows that have no NaN values

In [ ]:
print(iris_2d[~np.isnan(iris_2d).any(axis=1)])
# ~ negates condition, keeps rows with no NaN


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [5.4 3.4 1.5 0.4]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.

34. Find correlation between SepalLength & PetalLength

In [ ]:
print(np.corrcoef(iris_2d[:, 0], iris_2d[:, 2]))  # np.corrcoef() gives correlation matrix


[[ 1. nan]
 [nan nan]]


35. Check if any missing values exist in dataset

In [ ]:
print(np.isnan(iris_2d).any())              # True if there’s any NaN

True


# 36. Replace all NaN with 0

In [ ]:
iris_2d = np.nan_to_num(iris_2d)            # Converts NaN → 0
print(iris_2d[:3])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


 37. Find unique species and their counts

In [ ]:
unique_species, counts = np.unique(species, return_counts=True)
print(unique_species, counts)               # Displays distinct labels and count for each

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica'] [50 50 50]
